# ===========================================================================
# NEON Vegetation Structure Explorer — ui.R
# ===========================================================================
ui <- bslib::page_fillable(
  theme = app_theme,
  window_title = "NEON Vegetation Structure Explorer", fillable = FALSE,

  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/driver.js@1.3.1/dist/driver.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/driver.js@1.3.1/dist/driver.js.iife.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("veg.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  # ---- persistent top control bar (theme + help) -------------------------
  # The sidebar is gone in v2: the picker map IS the way to select a site, and
  # the by-name site picker now lives on the landing (the select-panel inside the
  # splash). The two controls that must stay reachable everywhere — the theme
  # toggle and the help dialog — sit in this slim top-right bar above the hero.
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", "\U0001F333"),
      tags$span(class = "tb-title", "Vegetation Structure")),
    div(class = "top-bar-actions",
      actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  div(id = "loadOverlay", class = "load-overlay",
    div(class = "load-card",
      div(class = "load-spin mascot-spin", MASCOT_CRITTER),
      div(class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar"),
      div(class = "load-note", "Building the stand-structure, growth, and size profiles."))),

  uiOutput("heroStats"),

  # "Open a tree's career" picker — was in the sidebar, now a hidden body block
  # revealed on site load (server: shinyjs::show("treePickerWrap")). Same ids
  # (treeSel, pickBiggest/Tallest/Fastest, surpriseBtn) so the server is untouched.
  hidden(div(id = "treePickerWrap", class = "tree-picker-wrap",
    div(class = "tpw-row",
      div(class = "tpw-sel",
        selectizeInput("treeSel", label = tagList(bs_icon("search"), " Open a tree's career"),
                       choices = NULL, width = "100%", options = list(placeholder = "Pick a tree…"))),
      div(class = "pick-chips",
        actionButton("pickBiggest", tagList(bs_icon("circle-fill"), " Biggest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickTallest", tagList(bs_icon("arrows-vertical"), " Tallest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickFastest", tagList(bs_icon("graph-up-arrow"), " Fastest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm")))
  )),

  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start!"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash",
      div(class = "app-hero app-hero-splash",
        h1(class = "app-title", "NEON Vegetation Structure Explorer", span(class = "title-tag", "unofficial")),
        p(class = "app-subtitle",
          "How woody plants are built across a continent. Every tagged tree and desert shrub's diameter and height, the stand's size structure, and how individuals grow over the years. 42 NEON sites, every biome (DP1.10098.001).")),
      p("Pick a ", tags$b("site"), " on the map below (or the Browse-all list, or by name). Forests are sized by tree ", tags$b("DBH"), "; deserts and shrublands by ", tags$b("basal stem diameter"), ". The app adapts. The Overview names each stand's own dominant species from its live data."),
      div(class = "splash-map-hint", bs_icon("hand-index-thumb"),
        " Tap a site to explore it. Dot size is how many stems were measured, colour is forest vs shrubland."),
      mapPickerUI("picker", height = "520px", spinner = DDL$green),

      # ---- relocated select panel (was the sidebar) ----------------------
      # Same input ids the server's cascade + load path depend on (stateSel,
      # site, loadBtn). Tapping a dot is the primary path; this panel is the
      # by-name fallback. Same ids, so server.R is untouched. (This app has no
      # date window, so the panel carries only the state + site pickers.)
      div(class = "select-panel",
        div(class = "sp-head", bs_icon("sliders"), " Or pick a site by name"),
        div(class = "sp-row",
          div(class = "sp-field",
            selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " State"),
                        choices = NULL, width = "100%")),
          div(class = "sp-field",
            selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"),
                        choices = NULL, width = "100%"))),
        uiOutput("siteBio"),
        actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                     class = "btn-primary btn-lg load-btn sp-load", onclick = "smtLoadStart()")),

      tags$details(class = "site-browse",
        tags$summary(
          tags$span(class = "sb-summary",
            tags$span(class = "sb-label", bs_icon("list-ul"), " Browse all 42 sites"),
            tags$span(class = "sb-chevron", bs_icon("chevron-down")))),
        div(class = "site-browse-body", uiOutput("siteCards"))),
      div(class = "picker-tour", actionLink("tourBtn", tagList(bs_icon("signpost-2"), " Take a quick tour"))))),

  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goStand", tagList(bs_icon("bar-chart-line-fill"), div("Stand Structure"), tags$small("size classes & basal area")), class = "home-btn"),
          actionButton("goGrowth", tagList(bs_icon("graph-up-arrow"), div("Growth & Mortality"), tags$small("how plants change")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Size Lab"), tags$small("every plant, pinnable")), class = "home-btn home-btn-star"),
          actionButton("goFame", tagList(bs_icon("trophy"), div("Champions"), tags$small("biggest · tallest · fastest")), class = "home-btn"),
          actionButton("goTree", tagList(bs_icon("tree"), div("Plant Career"), tags$small("one plant over time")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two stands"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What the stand is made of: species by basal area",
            info_pop("Composition",
              p("Each species' share of the stand's ", tags$b("basal area"), " (the summed cross-sectional area of all its stems), the standard measure of how much a species ", tags$em("occupies"), " a stand, weighting big plants over small. Computed at breast height for trees, at the base for shrubs."),
              p("Live, species-identified stems with a measured diameter."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("baBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data, the same numbers the rest of the app uses."))),
          uiOutput("siteInsights")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "This site vs the network",
            info_pop("Network context",
              p("Every bundled NEON site ranked by ", tags$b("species richness"), ". The ", tags$span(style="color:#E0A500;font-weight:700","gold bar"), " is the site you're viewing. Answers the question no site-local number can: ", tags$b("is this a lot?")),
              p("Richness here is the count of identified woody species in the site's bundle."))),
          spin(plotlyOutput("networkStrip", height = "520px")))),

      nav_panel(title = tagList(bs_icon("bar-chart-line-fill"), " Stand Structure"), value = "stand",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How is this stand built?"),
          p("The size-class distribution, basal area and stem density per hectare, and the height profile, the structural fingerprint of the stand."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("bar-chart-fill", "Size-class distribution",
              info_pop("Size classes",
                p("Live woody plants binned by stem diameter (cm). In ", tags$b("forests"), " that's tree ", tags$b("DBH ≥ 10 cm"), "; in ", tags$b("deserts/shrublands"), " it's ", tags$b("basal stem diameter"), " (shrubs are too short for a breast-height measurement)."),
                p("A descending “reverse-J” (many small, few large) is the signature of a ", tags$b("regenerating, uneven-aged"), " stand. For forests, smaller saplings are tallied in separate nested subplots over a smaller area, so they're excluded here to avoid a sampling artifact."),
                p("On forest stands the ", tags$b("dashed line"), " is the idealized reverse-J decline (a negative-exponential / de Liocourt trend) fit to this stand. Bars sitting ", tags$b("below"), " it in the small classes flag a possible ", tags$b("recruitment gap"), ", too few young trees coming up."))),
            uiOutput("sizeInsight"),
            spin(plotlyOutput("sizePlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("rulers", "Height profile",
              info_pop("Heights", p("The distribution of live-plant ", tags$b("heights"), " (m). Plants measured for diameter but not height aren't shown here."))),
            spin(plotlyOutput("htPlot", height = "340px")))),
        card(card_head("calculator", "Stand density, per hectare",
            info_pop("Per-hectare",
              p("Basal area (m²/ha) and stem density (stems/ha), scaled by each plot's ", tags$b("sampled tree area"), " then averaged, so a bigger plot doesn't dominate. Quadratic mean diameter (QMD) is the diameter of the tree of average basal area."),
              p(tags$em("These are stand-level indices from the sampled plots, not a wall-to-wall inventory.")))),
          uiOutput("densityBanner"))),

      nav_panel(title = tagList(bs_icon("graph-up-arrow"), " Growth & Mortality"), value = "growth",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How do the plants change?"),
          p("Diameter growth between remeasurements, the fastest growers, and the live/standing-dead breakdown. NEON remeasures most plots every ~5 years, so growth is per-year between visits."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Diameter growth rates",
              info_pop("Growth",
                p("Annualised stem-diameter increment (cm/yr) for plants measured at ", tags$b("two or more"), " visits, one rate per plant, DBH for trees, basal diameter for shrubs. Plants are remeasured every few years, so this is Δdiameter ÷ years between visits."),
                p("Some plants show a ", tags$b("decrease"), ", usually real (bark sloughing, drought, a changed measurement height), not an error; those are kept and flagged on the plant card."))),
            uiOutput("growthInsight"),
            spin(plotlyOutput("growthPlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("heart-pulse", "Mortality: annual rate & snapshot",
              info_pop("Mortality",
                p("Two different things, shown together. The ", tags$b("annual rate"), " (compound, Sheil & May) is ", tags$b("1 − (1 − deaths/N₀)^(1/years)"), " over the tracked cohort, the forestry standard, comparable across stands."),
                p("The pie is a ", tags$b("snapshot"), ": each tagged individual at its most recent visit, Live if ", tags$b("any"), " stem is live, ", tags$b("not"), " a rate."),
                p(tags$b("“Lost track / removed”"), " (lost tag, removed, no-longer-qualifies) is a data state, kept separate from biological ", tags$b("Dead"), " so neither the rate nor the pie misreads it as mortality."))),
            uiOutput("mortalityBanner"),
            spin(plotlyOutput("statusPlot", height = "300px")))),
        card(full_screen = TRUE,
          card_head("rulers", "Does growth slow with size?",
            info_pop("Size vs growth",
              p("Each dot is a remeasured plant: its ", tags$b("current diameter"), " (x) against its ", tags$b("annual growth"), " (y), coloured by species, the structural twin of the small-mammal Size Lab."),
              p("A ", tags$b("dashed trend line"), " is drawn ", tags$b("only"), " when the size–growth relationship is real (n ≥ 12, |Spearman r| ≥ 0.15, p < 0.05); otherwise it's an honest scatter with a “no clear trend” note, no fabricated line."))),
          spin(plotlyOutput("growthSize", height = "360px"))),
        card(card_head("trophy", "Fastest-growing plants",
            info_pop("Fastest growers", p("Plants ranked by annualised diameter growth (≥2 visits spanning ≥1 year), DBH for trees and basal diameter for shrubs. Implausible jumps (>5 cm/yr) are excluded as likely measurement issues, not champions."), p(tags$b("Tap a row"), " to open that plant's growth career."))),
          spin(DT::DTOutput("fastTable")))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Size Lab"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Every plant on one map",
               info_pop("Size Lab",
                 p("Each dot is a ", tags$b("plant"), ", placed by its ", tags$b("stem diameter"), " (x, DBH for trees, basal diameter for shrubs) and ", tags$b("height"), " (y), coloured by species. Median crosshairs split it into four shapes."),
                 p(tags$b("Tap a dot"), " to pin its card; drag, resize, and download the chart with the cards on it. Tap “Open career” for its full growth history."),
                 p("Plants measured for diameter but not height can't sit in this 2-D space; their count is noted below the plot."))),
            p("Each dot is a plant, size × height, by species. Tap to pin a card; open any plant's growth career.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Species" = "species", "Canopy position" = "canopyPosition", "Status" = "status"),
                        selected = "species", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Size × height, by plant",
            info_pop("Reading this", p("The four corners are the size-shape extremes (big-tall, thin-tall, big-short, small-short); the exact labels adapt to forests vs shrublands. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plant you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", spin(plotlyOutput("labScatter", height = "540px"))),
          uiOutput("labNote")),
        uiOutput("treeCardSlot")),

      nav_panel(title = tagList(bs_icon("trophy"), " Champions"), value = "fame",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The record-holders"),
          p("The biggest, tallest, fastest-growing, and longest-tracked plants at this site. Tap any one to open its full career."))),
        div(class = "leader-cats",
          radioButtons("fameMetric", NULL, inline = TRUE,
            choices = c("Biggest" = "biggest", "Tallest" = "tallest",
                        "Fastest grower" = "fastest", "Longest career" = "career"),
            selected = "biggest")),
        uiOutput("famePodium"),
        card(full_screen = TRUE,
          card_head("trophy", "Leaderboard",
            info_pop("Champions",
              p("Live plants ranked by the chosen metric. ", tags$b("Fastest grower"), " is the annualised diameter increment for remeasured plants (implausible >5 cm/yr jumps and changed measurement heights excluded). ", tags$b("Longest career"), " counts distinct measurement visits."),
              p("Tap a row to open that plant's career."))),
          spin(DT::DTOutput("fameTable")))),

      nav_panel(title = tagList(bs_icon("tree"), " Plant Career"), value = "tree",
        uiOutput("treeProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Each marker is a NEON plot, sized by basal area and coloured by the metric you choose. The selected plant's plot glows gold.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("Basal area (m²/ha)" = "ba_ha", "Stem density (/ha)" = "density_ha", "Species richness" = "n_species")),
            selectInput("view", "Basemap", width = "160px", selected = "CartoDB.Positron",
                        choices = c("Light" = "CartoDB.Positron", "Terrain" = "Esri.WorldTopoMap", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "620px")),
        card(class = "qc-card",
          card_head("clipboard-check", "Data-quality scan",
            info_pop("Data quality",
              p("Automated ", tags$b("verify-not-wrong"), " checks across this site's remeasured plants: impossible status flips, implausible diameter jumps, unexplained shrinks, moved measurement heights."),
              p("Tap a flag to inspect the exact plants and download them; nothing here is deleted. Flags are for review."),
              div(class = "evo-dl-row", downloadButton("vegQcReport", tagList(bs_icon("download"), " Full QC report (CSV)"), class = "btn-outline-dark btn-sm")))),
          uiOutput("vegQcFlags"))),

      nav_panel(title = tagList(bs_icon("search"), " Search"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the network"),
          p("Look across every bundled NEON site at once, with no loading and no download. Find which sites a woody species grows at, or list the sites that pass a size threshold, then jump straight into any one."))),
        div(class = "search-mode",
          radioButtons("searchMode", NULL, inline = TRUE,
            choices = c("Find a species" = "taxon", "Sites by size" = "threshold"),
            selected = "taxon")),

        conditionalPanel("input.searchMode == 'taxon'",
          card(
            card_head("tree", "Find a species across the network",
              info_pop("Find a species",
                p("Pick any woody species recorded at a bundled site. The table lists every site where it grows, with that species' live ", tags$b("basal area"), " (m²/ha) and live ", tags$b("stem count"), " at the site, and the years it was measured."),
                p("Basal area is area-standardized within each site (summed stem cross-section over the sampled plot area), an honest ", tags$b("within-site"), " amount, not an absolute cross-site ranking. Forest sites are sized by DBH and shrubland sites by basal stem diameter, which are different measurements, so the structure column is shown."))),
            div(class = "search-pick",
              selectizeInput("taxonPick", "Woody species", choices = NULL, width = "100%",
                options = list(placeholder = "Start typing a scientific name, e.g. Quercus..."))),
            uiOutput("taxonCount"),
            div(style = "width:100%", DT::DTOutput("taxonHits")),
            div(class = "search-cap", bs_icon("info-circle"),
              " The measure is a within-site index from the sampled plots, not a wall-to-wall count. Tap a row to load that site and open its Overview."))),

        conditionalPanel("input.searchMode == 'threshold'",
          card(
            card_head("rulers", "Sites by size threshold",
              info_pop("Sites by size",
                p("List the sites whose stand passes a size threshold. ", tags$b("Basal area"), " (m²/ha) is the live stand's cross-sectional stocking; ", tags$b("biggest stem"), " and ", tags$b("tallest plant"), " are the site's record sizes."),
                p("Forest sites (sized by DBH at breast height) and shrubland sites (sized by basal stem diameter at the base) measure size differently, so these aren't a single absolute ranking; the structure column tells you which paradigm each row is. Filter to one structure type to compare like with like."))),
            div(class = "search-controls",
              selectInput("threshMetric", "Rank / filter by", width = "240px",
                choices = c("Basal area (m²/ha)" = "ba_ha", "Biggest stem (cm)" = "biggest", "Tallest plant (m)" = "tallest")),
              selectInput("threshType", "Structure", width = "180px",
                choices = c("All sites" = "all", "Forest only" = "forest", "Shrubland only" = "shrubland")),
              div(class = "thresh-slider", uiOutput("threshSliderUI"))),
            uiOutput("threshCount"),
            div(style = "width:100%", DT::DTOutput("threshHits")),
            div(class = "search-cap", bs_icon("info-circle"),
              " Stand indices from the sampled plots, not a wall-to-wall inventory; size measures differ between forest and shrubland sites. Tap a row to load that site and open its Overview.")))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Vegetation Structure (DP1.10098.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
