# ===========================================================================
# NEON Vegetation Structure Explorer — ui.R
# ===========================================================================
ui <- bslib::page_fillable(
  theme = app_theme,
  window_title = "NEON Vegetation Structure Explorer", fillable = FALSE,

  tags$head(
    tags$link(rel = "stylesheet", href = asset_url("vendor/sweetalert2/sweetalert2.min.css")),
    tags$script(src = asset_url("vendor/sweetalert2/sweetalert2.all.min.js")),
    tags$script(src = asset_url("vendor/html-to-image/html-to-image.js")),
    tags$link(rel = "stylesheet", href = asset_url("vendor/driver/driver.css")),
    tags$script(src = asset_url("vendor/driver/driver.js.iife.js")),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("veg.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  tags$a(class = "app-skip-link", href = "#appMain", "Skip to app content"),

  # ---- persistent top control bar -----------------------------------------
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", MEASURE_MARK),
      tags$span(class = "tb-title", "Vegetation Structure")),
    div(class = "top-bar-actions",
      actionButton("browsePlaces", tagList(bs_icon("geo-alt"), tags$span(class = "tb-action-text", " Places")),
                   class = "btn-outline-dark btn-sm tb-places"),
      actionButton("help", tagList(bs_icon("question-circle"), tags$span(class = "tb-action-text", " How it works")),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  div(id = "loadOverlay", class = "load-overlay", role = "dialog",
      `aria-modal` = "true", `aria-live` = "polite", `aria-busy` = "true",
      `aria-hidden` = "true", `aria-labelledby` = "loadTitle", tabindex = "-1",
    div(class = "load-card",
      div(class = "load-spin measure-spin", MEASURE_MARK),
      div(id = "loadTitle", class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar"),
      div(class = "load-note", "Opening the measurements and building this place's view."))),

  tags$main(id = "appMain", tabindex = "-1",

  uiOutput("heroStats"),

  # "Open a plant record" picker — a hidden body block revealed after site load.
  # revealed on site load (server: shinyjs::show("treePickerWrap")). Same ids
  # (treeSel, pickBiggest/Tallest/Fastest, surpriseBtn) so the server is untouched.
  hidden(div(id = "treePickerWrap", class = "tree-picker-wrap",
    div(class = "tpw-row",
      div(class = "tpw-sel",
        selectizeInput("treeSel", label = tagList(bs_icon("search"), " Open a plant record"),
                       choices = NULL, width = "100%", options = list(placeholder = "Pick a plant…"))),
      uiOutput("channelPicker"),
      div(class = "pick-chips",
        actionButton("pickBiggest", tagList(bs_icon("circle-fill"), " Biggest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickTallest", tagList(bs_icon("arrows-vertical"), " Tallest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickFastest", tagList(bs_icon("graph-up-arrow"), " Most positive change"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm")))
  )),

  div(id = "splash",
    div(class = "living-poster-app",
      div(class = "lpa-copy",
        div(class = "lpa-kicker", "NEON VEGETATION STRUCTURE", span("unofficial")),
        h1("Tagged. Measured. ", em("Still changing.")),
        p(class = "lpa-promise", "Follow real trees and shrubs through years of change."),
        div(class = "lpa-trust",
          span(bs_icon("geo-alt-fill"), " 42 places"),
          span(bs_icon("tag-fill"), " real tagged plants"),
          span(bs_icon("database-fill"), " public measurements")),
        tags$a(class = "lpa-skip", href = "#placeGateway", "Pick a place ", bs_icon("arrow-down"))),
      figure(class = "lpa-art",
        tags$img(src = asset_url("assets/vegetation-living-poster.png"),
          alt = "Editorial illustration of a tagged tree with a diameter tape and a shrub measured at its base."),
        tags$figcaption("Editorial illustration—not a field photograph or data record."))),

    div(id = "placeGateway", class = "place-gateway",
      div(class = "pg-head",
        div(
          div(class = "pg-kicker", "START HERE"),
          h2("Pick a place"),
          p("Tap the map, choose by name, or search all 42 places first.")),
        div(class = "pg-actions",
          actionButton("searchNetworkBtn", tagList(bs_icon("search"), " Search every place"),
                       class = "btn-outline-dark"),
          actionLink("tourBtn", tagList(bs_icon("signpost-2"), " Quick tour")))),
      div(class = "splash-map-hint", bs_icon("hand-index-thumb"),
        " Dot size reflects supported live plants; colour separates tree-DBH from shrub/sapling measurement channels. Grey or held places are unknown—not zero."),
      mapPickerUI("picker", height = "500px", spinner = DDL$green),
      div(class = "select-panel select-panel-compact",
        div(class = "sp-field",
          selectizeInput("site", label = tagList(bs_icon("pin-map-fill"), " Choose by name"),
                         choices = NULL, width = "100%",
                         options = list(placeholder = "Type a site code, place, or state…"))),
        actionButton("loadBtn", tagList(bs_icon("arrow-right-circle-fill"), " Open this place"),
                     class = "btn-primary btn-lg load-btn sp-load", onclick = "smtLoadStart()"),
        uiOutput("siteBio"))
    )),

  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("geo-alt-fill"), " Place"), value = "overview",
        div(class = "home-nav",
          actionButton("goStand", tagList(bs_icon("bar-chart-line-fill"), div("What was measured?"), tags$small("shape, height, density")), class = "home-btn"),
          actionButton("goGrowth", tagList(bs_icon("graph-up-arrow"), div("How did it change?"), tags$small("growth and mortality")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Find a plant"), tags$small("supported tagged plants")), class = "home-btn home-btn-star")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two places"), class = "btn-outline-dark btn-sm"),
          actionButton("goSearch", tagList(bs_icon("search"), " Search the network"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "Which identifications contribute to the measured structure?",
            info_pop("Composition",
              p("Each taxon or field identification's equal-plot contribution to measured stem cross-section within this site's active, supported physical channel."),
              p("Each supported plot contributes equally after its exact sampled area is applied. Detection and identification effort still affect what is represented."),
              p("Tree DBH area and shrub basal-cover area are kept separate. This is sampled contribution—not proof of ecological dominance."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("baBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data, the same numbers the rest of the app uses."))),
          uiOutput("siteInsights")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "This place across the network",
            info_pop("Network context",
              p("Bundled sites lined up by observed woody-species count. The ", tags$span(style="color:#E0A500;font-weight:700","gold bar"), " is the current place."),
              p("This is discovery context, not a biodiversity ranking: plots, stem records, years, and detection effort differ by site."))),
          spin(plotlyOutput("networkStrip", height = "520px")))),

      nav_panel(title = tagList(bs_icon("graph-up-arrow"), " Change"), value = "growth",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How do the plants change?"),
          p("Like-for-like diameter change between supported remeasurements, plus transparent status and cohort-mortality summaries."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Annualized diameter change",
              info_pop("Growth",
                p("Annualised diameter change for plot + plant identities with at least two comparable supported events. DBH changes require a stable measurement point."),
                p("Unalignable multi-stem basal records are held rather than forced into a trajectory. Decreases are retained and flagged because they can reflect biology, damage, or measurement differences."))),
            uiOutput("growthInsight"),
            spin(plotlyOutput("growthPlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("heart-pulse", "Mortality: annual rate & snapshot",
              info_pop("Mortality",
                p("Two different descriptive summaries. The compound cohort rate uses transitions from any-live to all-dead across comparable events and each plant's observed interval; uncertainty uses a delete-one-plot jackknife."),
                p("The pie is a ", tags$b("snapshot"), ": each plot + plant at its latest supported event, Live if ", tags$b("any"), " stem is live. It is not a rate."),
                p(tags$b("“Lost track / removed”"), " (lost tag, removed, no-longer-qualifies) is a data state, kept separate from biological ", tags$b("Dead"), " so neither the rate nor the pie misreads it as mortality."))),
            uiOutput("mortalityBanner"),
            spin(plotlyOutput("statusPlot", height = "300px")))),
        card(full_screen = TRUE,
          card_head("rulers", "Does growth slow with size?",
            info_pop("Size vs growth",
              p("Each dot is a remeasured plant: its ", tags$b("last supported recorded diameter"), " (x) against its ", tags$b("annualized diameter change"), " (y), coloured by species."),
              p("A dashed descriptive line appears only after a prespecified screen (n ≥ 12, |Spearman r| ≥ 0.15, p < 0.05). Passing the screen does not prove that size caused the pattern."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSave('growthSizeBox','NEON-VegStructure_<site>_size-vs-growth_<date>.png')", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins('growthSizeBox')", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "growthSizeBox", spin(plotlyOutput("growthSize", height = "360px")))),
        card(card_head("trophy", "Greatest positive diameter changes",
            info_pop("Positive diameter change", p("Plants ranked within the active compatible channel by annualized diameter change. Changed measurement points, unalignable multi-stem basal records, and display outliers are excluded from the leaderboard but retained in downloads."), p(tags$b("Tap a row"), " to open that plant's record."))),
          spin(DT::DTOutput("fastTable")))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Plant"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Measured plants on one map",
               info_pop("Size Lab",
                 p("Each dot is a supported plant with both measurements needed for this view: ", tags$b("stem diameter"), " (x, DBH for trees, basal diameter for shrubs) and ", tags$b("height"), " (y), coloured by species. Median crosshairs split it into four shapes."),
                 p(tags$b("Tap a dot"), " to pin its card; drag, resize, and download the chart with the cards on it. Tap “Open career” for its full growth history."),
                 p("Plants measured for diameter but not height can't sit in this 2-D space; their count is noted below the plot."))),
            p("Each dot is a plant, size × height, by species. Tap to pin a card; open any plant's growth career.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Species" = "species", "Canopy position" = "canopyPosition", "Status" = "status"),
                        selected = "species", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Size × height, by plant",
            info_pop("Reading this", p("The four corners are geometric size-shape extremes (big-tall, small-tall, big-short, small-short). They are not life stages. The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the plant you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSave('labScatterBox','NEON-VegStructure_<site>_size-lab_<date>.png')", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins('labScatterBox')", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "labScatterBox", spin(plotlyOutput("labScatter", height = "540px"))),
          uiOutput("labNote")),
        uiOutput("treeCardSlot")),

      nav_menu(title = tagList(bs_icon("grid-fill"), " More"),

      nav_panel(title = tagList(bs_icon("bar-chart-line-fill"), " Sampled Structure"), value = "stand",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("What did the supported plots measure?"),
          p("A descriptive size distribution, measured cross-sectional area, stem density, and height profile—without turning unsupported opportunities into zeros."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("bar-chart-fill", "Size-class distribution",
              info_pop("Size classes",
                p("Live measured stems binned by a channel-compatible diameter. Large-tree DBH records use the tree area; nested shrub/sapling records use their separate sampled area."),
                p("The bars describe the observed size shape only. A snapshot cannot establish recruitment, regeneration, or stand age, so no expected curve is imposed."))),
            uiOutput("sizeInsight"),
            spin(plotlyOutput("sizePlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("rulers", "Height profile",
              info_pop("Heights", p("The distribution of live-plant ", tags$b("heights"), " (m). Plants measured for diameter but not height aren't shown here."))),
            spin(plotlyOutput("htPlot", height = "340px")))),
          card(card_head("calculator", "Supported sampled-plot summary",
            info_pop("Per-hectare",
              p("Measured cross-sectional area (m²/ha) and stem density use each plot-event's exact compatible sampled area, then summarize supported plots. Every valid positive area—including small 40 m² nested areas—is retained."),
              p("Sampled absence is zero; impractical, dendrometer-only, invalid-area, invalid-required-diameter, and unmatched opportunities are held. QMD is stem-weighted. Nothing here is a wall-to-wall inventory."))),
          uiOutput("densityBanner"))),

      nav_panel(title = tagList(bs_icon("trophy"), " Champions"), value = "fame",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Standout sampled records"),
          p("The biggest, tallest, fastest-changing, and longest-tracked plants among supported records in the active channel. Tap any one to open its preserved record."))),
        div(class = "leader-cats",
          radioButtons("fameMetric", NULL, inline = TRUE,
            choices = c("Biggest" = "biggest", "Tallest" = "tallest",
                        "Greatest positive change" = "fastest", "Longest career" = "career"),
            selected = "biggest")),
        uiOutput("famePodium"),
        card(full_screen = TRUE,
          card_head("trophy", "Leaderboard",
            info_pop("Champions",
              p("Live plants ranked by the chosen metric. ", tags$b("Greatest positive change"), " is the annualized diameter change for remeasured plants after the stated display screen (>5 cm/yr and changed measurement heights excluded). ", tags$b("Longest career"), " counts distinct supported measurement events."),
              p("Tap a row to open that plant's career."))),
          spin(DT::DTOutput("fameTable")))),

      nav_panel(title = tagList(bs_icon("tree"), " Plant Career"), value = "tree",
        uiOutput("treeProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Supported NEON plot summaries carry measured values. Held opportunities stay visible in grey with unavailable values—not zero.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("Measured area index (m²/ha)" = "ba_ha", "Stem density (/ha)" = "density_ha", "Recorded taxa" = "n_taxa")),
            selectInput("view", "Basemap", width = "160px", selected = "CartoDB.Positron",
                        choices = c("Light" = "CartoDB.Positron", "Terrain" = "Esri.WorldTopoMap", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "620px")),
        card(class = "qc-card",
          card_head("clipboard-check", "Data-quality scan",
            info_pop("Data quality",
              p("Automated ", tags$b("verify-not-wrong"), " checks across this site's remeasured plants: status reversals incompatible with the mortality contract, large diameter changes, and moved measurement points."),
              p("Tap a flag to inspect the exact plants and download them; nothing here is deleted. Flags are for review."),
              div(class = "evo-dl-row", downloadButton("vegQcReport", tagList(bs_icon("download"), " Full QC report (CSV)"), class = "btn-outline-dark btn-sm")))),
          uiOutput("vegQcFlags"))),

      nav_panel(title = tagList(bs_icon("search"), " Search"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the network"),
          p("Look across every bundled NEON site at once. Find where a woody species was recorded, or filter supported sampled summaries within one compatible measurement channel, then jump into any place."))),
        div(class = "search-mode",
          radioButtons("searchMode", NULL, inline = TRUE,
            choices = c("Find a species" = "taxon", "Sites by size" = "threshold"),
            selected = "taxon")),

        conditionalPanel("input.searchMode == 'taxon'",
          card(
            card_head("tree", "Find a species across the network",
              info_pop("Find a species",
                p("Pick a recorded woody species. Each row shows its supported sampled-plot measurement, live stem records, and the years of the latest supported plot events represented."),
                p("Tree DBH area and shrub basal-cover area are different physical channels. Rows are grouped by channel and site—not ranked across unlike measurements."))),
            div(class = "search-pick",
              selectizeInput("taxonPick", "Woody species", choices = NULL, width = "100%",
                options = list(placeholder = "Start typing a scientific name, e.g. Quercus..."))),
            uiOutput("taxonCount"),
            div(style = "width:100%", DT::DTOutput("taxonHits")),
            div(class = "search-cap", bs_icon("info-circle"),
              " Sampled absence is retained as zero; unsupported opportunities remain held/NA. Tap a row to open its source place."))),

        conditionalPanel("input.searchMode == 'threshold'",
          card(
            card_head("rulers", "Sites by size threshold",
              info_pop("Sites by size",
                p("Filter supported sampled summaries by measured area, biggest stem, or tallest measured plant. Every supported site × physical channel appears independently."),
                p("For area or diameter, first choose Tree DBH or Shrub & sapling basal. Those measurements are not one comparable scale."))),
            div(class = "search-controls",
              selectInput("threshMetric", "Rank / filter by", width = "240px",
                choices = c("Measured area index (m²/ha)" = "ba_ha", "Biggest measured stem (cm)" = "biggest", "Tallest measured plant (m)" = "tallest")),
              selectInput("threshType", "Measurement channel", width = "240px",
                choices = c("All supported channels" = "all", "Tree DBH" = "tree_dbh", "Shrub & sapling basal" = "shrub_sapling_basal")),
              div(class = "thresh-slider", uiOutput("threshSliderUI"))),
            uiOutput("threshCount"),
            div(style = "width:100%", DT::DTOutput("threshHits")),
            div(class = "search-cap", bs_icon("info-circle"),
              " Each row is one supported site × physical channel—not a whole-site classification. Record sizes and observed richness also vary with sampling effort.")))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
      )
    )),

  ),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Vegetation Structure (DP1.10098.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
