# ===========================================================================
# NEON Vegetation Structure Explorer — ui.R
# ===========================================================================
ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Vegetation Structure Explorer", fillable = FALSE,

  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/driver.js@1.3.1/dist/driver.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/driver.js@1.3.1/dist/driver.js.iife.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("veg.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  sidebar = sidebar(
    width = 320, class = "control-deck",
    div(class = "brand",
      div(class = "brand-mark", "\U0001F332"),
      div(div(class = "brand-title", "Vegetation Structure"),
          div(class = "brand-sub", "Tagged trees · remeasured"))),
    selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " 1 · Pick a state"), choices = NULL, width = "100%"),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " 2 · Pick a site"), choices = NULL, width = "100%"),
    uiOutput("siteBio"),
    actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                 class = "btn-primary btn-lg w-100 load-btn", onclick = "smtLoadStart()"),
    actionButton("demoBtn", tagList(bs_icon("stars"), " or open the Harvard Forest demo (instant)"),
                 class = "btn-link btn-sm w-100 reset-demo", onclick = "smtLoadStart('Harvard Forest — demo dataset')"),
    hidden(div(id = "treePickerWrap",
      hr(class = "deck-hr"),
      selectizeInput("treeSel", label = tagList(bs_icon("search"), " Open a tree's career"),
                     choices = NULL, options = list(placeholder = "Pick a tree…")),
      div(class = "pick-chips",
        actionButton("pickBiggest", tagList(bs_icon("circle-fill"), " Biggest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickTallest", tagList(bs_icon("arrows-vertical"), " Tallest"), class = "btn-outline-dark btn-sm pick-chip"),
        actionButton("pickFastest", tagList(bs_icon("graph-up-arrow"), " Fastest"), class = "btn-outline-dark btn-sm pick-chip")),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm w-100"))),
    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How it works"), class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row",
      tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "deck-foot",
      bs_icon("database"), " NEON ", tags$code("DP1.10098.001"),
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank", bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),

  div(id = "loadOverlay", class = "load-overlay",
    div(class = "load-card",
      div(class = "load-spin", "\U0001F332"),
      div(class = "load-title", "Loading site data"),
      div(id = "loadSite", class = "load-site"),
      div(class = "load-bar"),
      div(class = "load-note", "Building the stand-structure, growth, and size profiles."))),

  uiOutput("heroStats"),

  div(id = "splash",
    div(class = "splash",
      div(class = "app-hero app-hero-splash",
        h1(class = "app-title", "NEON Vegetation Structure Explorer", span(class = "title-tag", "unofficial")),
        p(class = "app-subtitle",
          "How NEON's forests are built — every tagged tree's diameter and height, the stand's size structure, and how individual trees grow over the years. Built on the woody vegetation survey (DP1.10098.001).")),
      p("Pick a ", tags$b("site"), " below, or open the Harvard Forest demo — a New England mixed hardwood–conifer forest. The Overview names each stand's own dominant species from its live data."),
      uiOutput("siteCards"),
      div(class = "picker-actions",
        actionButton("demoBtn2", tagList(bs_icon("stars"), " Open the Harvard Forest demo instantly"),
                     class = "btn-outline-dark btn-lg", onclick = "smtLoadStart('Harvard Forest — demo dataset')")),
      div(class = "picker-tour", actionLink("tourBtn", tagList(bs_icon("signpost-2"), " Take a quick tour"))))),

  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    navset_card_tab(id = "tabs",

      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goStand", tagList(bs_icon("bar-chart-line-fill"), div("Stand Structure"), tags$small("size classes & basal area")), class = "home-btn"),
          actionButton("goGrowth", tagList(bs_icon("graph-up-arrow"), div("Growth & Mortality"), tags$small("how trees change")), class = "home-btn"),
          actionButton("goLab", tagList(bs_icon("bullseye"), div("Forest Size Lab"), tags$small("every tree, pinnable")), class = "home-btn home-btn-star"),
          actionButton("goFame", tagList(bs_icon("trophy"), div("Champion Trees"), tags$small("biggest · tallest · fastest")), class = "home-btn"),
          actionButton("goTree", tagList(bs_icon("tree"), div("Tree Career"), tags$small("one tree over time")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("plots across the site")), class = "home-btn")),
        div(class = "tools-strip",
          actionButton("compareBtn", tagList(bs_icon("layout-split"), " Compare two stands"), class = "btn-outline-dark btn-sm"),
          downloadButton("allDataZip", "Download all data (CSV)", class = "btn-outline-dark btn-sm"),
          downloadButton("reportPdf", "Stand report (PDF)", class = "btn-outline-dark btn-sm")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "What the forest is made of — species by basal area",
            info_pop("Composition",
              p("Each species' share of the stand's ", tags$b("basal area"), " (the cross-sectional area of all its trunks at breast height) — the standard forestry measure of how much a species ", tags$em("occupies"), " a stand, weighting big trees over small."),
              p("Live, species-identified stems with a diameter at breast height (DBH)."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("baBar", height = "440px"))),
        card(card_head("stars", "The story so far",
            info_pop("Story", p("Written from this site's live data — the same numbers the rest of the app uses."))),
          uiOutput("siteInsights"))),

      nav_panel(title = tagList(bs_icon("bar-chart-line-fill"), " Stand Structure"), value = "stand",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How is this stand built?"),
          p("The size-class distribution, basal area and stem density per hectare, and the height profile — the structural fingerprint of the forest."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("bar-chart-fill", "Diameter size-class distribution",
              info_pop("Size classes",
                p("Live ", tags$b("trees ≥ 10 cm"), " diameter at breast height, binned (cm). A descending “reverse-J” (many small, few large) is the signature of a ", tags$b("regenerating, uneven-aged"), " stand; a top-heavy curve can signal an aging or even-aged stand."),
                p(tags$b("Trees ≥ 10 cm only"), " — smaller saplings are tallied in separate nested subplots over a smaller area, so including them here would under-represent the small classes as a sampling artifact."))),
            uiOutput("sizeInsight"),
            spin(plotlyOutput("sizePlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("rulers", "Height profile",
              info_pop("Heights", p("The distribution of live-tree ", tags$b("heights"), " (m). Trees measured for girth but not height aren't shown here."))),
            spin(plotlyOutput("htPlot", height = "340px")))),
        card(card_head("calculator", "Stand density — per hectare",
            info_pop("Per-hectare",
              p("Basal area (m²/ha) and stem density (stems/ha), scaled by each plot's ", tags$b("sampled tree area"), " then averaged — so a bigger plot doesn't dominate. Quadratic mean diameter (QMD) is the diameter of the tree of average basal area."),
              p(tags$em("These are stand-level indices from the sampled plots, not a wall-to-wall inventory.")))),
          uiOutput("densityBanner"))),

      nav_panel(title = tagList(bs_icon("graph-up-arrow"), " Growth & Mortality"), value = "growth",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("How do the trees change?"),
          p("Diameter growth between remeasurements, the fastest growers, and the live/standing-dead breakdown. NEON remeasures most plots every ~5 years, so growth is per-year between visits."))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Diameter growth rates",
              info_pop("Growth",
                p("Annualised diameter increment (cm/yr) for trees measured at ", tags$b("two or more"), " visits, one rate per tree. Trees are remeasured every few years, so this is Δdiameter ÷ years between visits."),
                p("Some trees show a ", tags$b("decrease"), " — usually real (bark sloughing, drought, a changed measurement height), not an error; those are kept and flagged on the tree card."))),
            uiOutput("growthInsight"),
            spin(plotlyOutput("growthPlot", height = "340px"))),
          card(full_screen = TRUE,
            card_head("heart-pulse", "Live vs standing dead",
              info_pop("Status",
                p("Each tagged ", tags$b("tree"), " (one per individual) at its most recent visit, classed Live if ", tags$b("any"), " of its boles is live. A snapshot ratio, ", tags$b("not"), " an annual mortality rate."),
                p(tags$b("“Lost track / removed”"), " (lost tag, removed, no-longer-qualifies) is a data state — kept separate from biological ", tags$b("Dead"), " so it isn't read as mortality."))),
            spin(plotlyOutput("statusPlot", height = "340px")))),
        card(card_head("trophy", "Fastest-growing trees",
            info_pop("Fastest growers", p("Trees ranked by annualised diameter growth (≥2 visits spanning ≥1 year). Implausible jumps (>5 cm/yr) are excluded as likely measurement issues, not champions."))),
          spin(DT::DTOutput("fastTable")))),

      nav_panel(title = tagList(bs_icon("bullseye"), " Forest Size Lab"), value = "lab",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Every tree on one map",
               info_pop("Forest Size Lab",
                 p("Each dot is a ", tags$b("tree"), ", placed by its ", tags$b("diameter"), " (x) and ", tags$b("height"), " (y), coloured by species. Median crosshairs split it into four shapes."),
                 p(tags$b("Tap a dot"), " to pin its card; drag, resize, and download the chart with the cards on it. Tap “Open tree career” for its full growth history."),
                 p("Trees measured for girth but not height can't sit in this 2-D space; their count is noted below the plot."))),
            p("Each dot is a tree — diameter × height, by species. Tap to pin a card; open any tree's growth career.")),
          div(class = "sizelab-controls",
            selectInput("labColor", tagList(bs_icon("palette"), " Colour by"),
                        choices = c("Species" = "species", "Canopy position" = "canopyPosition", "Status" = "status"),
                        selected = "species", width = "200px"))),
        card(full_screen = TRUE,
          card_head("bullseye", "Diameter × height, by tree",
            info_pop("Reading this", p("Top-right = big old ", tags$b("Giants"), "; top-left = thin tall ", tags$b("Spires"), " (fast young or suppressed); bottom-right = thick short ", tags$b("Stout"), " (broken-top / open-grown); bottom-left = ", tags$b("Saplings"), ". The ", tags$span(style="color:#c9a300;font-weight:700","gold diamond"), " is the tree you're viewing."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", spin(plotlyOutput("labScatter", height = "540px"))),
          uiOutput("labNote")),
        uiOutput("treeCardSlot")),

      nav_panel(title = tagList(bs_icon("trophy"), " Champion Trees"), value = "fame",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The record-holders"),
          p("The biggest, tallest, fastest-growing, and longest-tracked trees at this site. Tap any tree to open its full career."))),
        div(class = "leader-cats",
          radioButtons("fameMetric", NULL, inline = TRUE,
            choices = c("Biggest DBH" = "biggest", "Tallest" = "tallest",
                        "Fastest grower" = "fastest", "Longest career" = "career"),
            selected = "biggest")),
        uiOutput("famePodium"),
        card(full_screen = TRUE,
          card_head("trophy", "Leaderboard",
            info_pop("Champion trees",
              p("Live trees ranked by the chosen metric. ", tags$b("Fastest grower"), " is the annualised diameter increment for remeasured trees (implausible >5 cm/yr jumps and changed measurement heights excluded). ", tags$b("Longest career"), " counts distinct measurement visits."),
              p("Tap a row to open that tree's career."))),
          spin(DT::DTOutput("fameTable")))),

      nav_panel(title = tagList(bs_icon("tree"), " Tree Career"), value = "tree",
        uiOutput("treeProfile")),

      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head",
          div(class = "tab-head-text",
            h4("Plots across the site"),
            p("Each marker is a NEON plot, sized by basal area and coloured by the metric you choose. The selected tree's plot glows gold.")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "180px",
                        choices = c("Basal area (m²/ha)" = "ba_ha", "Stem density (/ha)" = "density_ha", "Species richness" = "n_species")),
            selectInput("view", "Basemap", width = "160px", selected = "CartoDB.Positron",
                        choices = c("Light" = "CartoDB.Positron", "Terrain" = "Esri.WorldTopoMap", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "620px"))),

      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),

  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta",
      href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer",
      span(class = "hand", "\U0001F44B"), "Want a custom data app like this for your project?")),
    p(style = "margin-top:12px",
      HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · feedback or custom dashboards → "),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Vegetation%20Structure%20Explorer", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85",
      "Data: NEON Vegetation Structure (DP1.10098.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
